### ISSUE TITLE
Manifest version 3 update checklist

### ISSUE THREAD

**Issue by Skeletonxf** [Skeletonxf/image-extract#3]
- [x] Image Extract uses a persistent background page, this will need migrating to a non persistent one. Image Extract has very little state in that background page so this should be straightforward.
- [x] Browser action APIs have changed namespace. Since the APIs are the same this should be a trivial update.
- [x] Image Extract uses the `executeScript` and `insertCSS` APIs, these will need migrating to the new Scripting API. Only files were injected into pages so the new API restrictions shouldn't be an issue.
- [x] This migration is a good opportunity to adopt newer JavaScript language features more broadly.
- [x] The minimum supported Firefox version will need increasing to whatever version of FF ships MV3 first, regardless of which version this is, it should be more than new enough for adopting modern JavaScript language features.
- [x] ~~Maybe a good time to drop (the redundant) support for turning off the keyboard shortcuts? Can we programmatically check what the keyboard shortcuts were set to so we can convert the boolean on/off settings to shortcut set/unset to provide an automatic migration for existing users?~~ - Don't think there's ever been an API to change shortcut values programmatically
- [x] Fix Firefox for Android not being able to get the UI settings via communication with the background script: https://discourse.mozilla.org/t/could-not-establish-connection-receiving-end-does-not-exist-only-on-firefox-for-android/113365

**Comment by Skeletonxf** [comment]
Version 2 uploaded to the AMO https://addons.mozilla.org/en-GB/firefox/addon/image-extract/
